apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mysql-spring-boot-example
  labels:
    app: docker-mysql-spring-boot-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-mysql-spring-boot-example
  template:
    metadata:
      labels:
        app: docker-mysql-spring-boot-example
    spec:
      containers:
      - name: docker-mysql-spring-boot-example

        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://db-mysql:3306/my-database

          - name: SPRING_DATASOURCE_USERNAME
            value: my-user

          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-mysql
                key: mysql-password

        image: bogdangi/docker-mysql-spring-boot-example:0.0.1

        ports:
        - containerPort: 8086
          name: http
          protocol: TCP

        livenessProbe:
          httpGet:
            path: /all/
            port: http

        readinessProbe:
          httpGet:
            path: /all/
            port: http
