apiVersion: v1
kind: Service
metadata:
  name: docker-mysql-spring-boot-example
  labels:
    app: docker-mysql-spring-boot-example
spec:
  ports:
  - port: 80
    targetPort: http
    name: http
    protocol: TCP
  type: NodePort
  selector:
    app: docker-mysql-spring-boot-example
